{{- if not .Values.clusterAgent.tokenExistingSecret }}
{{- if eq (include "should-deploy-cluster-agent" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clusterAgent.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "datadog.labels" . | indent 4 }}
{{- if .Values.datadog.secretAnnotations }}
  annotations: {{ toYaml .Values.datadog.secretAnnotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  {{ if .Values.clusterAgent.token -}}
  token: {{ .Values.clusterAgent.token | b64enc | quote }}
  {{- $ddgc-secret := (lookup "v1" "Secret" "datadog" "datadog-cluster-agent")
  {{ else if ne $ddgc-secret "" -}}
  token: {{ $ddgc-secret.data.token }}
  {{ else -}}
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
{{- end }}
{{ end }}
